
# 使用h2控制台
spring:
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

#elasticsearch文档
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      client:
        reactive:
          connection-timeout: 120
   
logging:
  pattern:
    level: debug
     
server: 
  port: 8080
  #servlet: 
    #context-path: /zachary
    