server: 
  port: 8080
  #servlet: 
    #context-path: /zachary
    
# 使用druid控制台
spring: 
  profiles:
    active: dev
---
spring: 
  profiles:
    active: prod
  mvc:
    dispatch-options-request: true
    view:      prefix: /WEB-INF/templates/
      suffix: .jsp
  redis:    host: localhost
    port: 6379
    password: redis
    database: 0
    timeout: 5000ms 
    lettuce:
      pool:
        max-active: 8         # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 1ms         # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8           # 连接池中的最大空闲连接 默认 8
        min-idle: 0           # 连接池中的最小空闲连接 默认 0
    #cluster:
      #max-redirects: 3  # 获取失败 最大重定向次数 
      #nodes:
        #- 192.168.1.236:7001
        #- 192.168.1.236:7002
        #- 192.168.1.236:7003
        #- 192.168.1.244:7004
        #- 192.168.1.244:7005
        #- 192.168.1.244:7006 
    
  datasource: 
      name: springboot2mysql
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?serverTimezone=GMT%2B8&?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root123
      cluster:
      - key: slave1
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave1?serverTimezone=GMT%2B8&?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root123
      - key: slave2
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave1?serverTimezone=GMT%2B8&?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root123
        
      #druid相关配置  
      druid:
                        #监控统计拦截的filters
        filters: stat,wall,slf4j,config
        initial-size: 5
        max-active: 200
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
        
                      # 配置监控服务器
        stat-view-servlet:
          enabled: true
          reset-enable: true
          login-username: admin
          login-password: 123456
          url-pattern: /druid/*
          allow: 127.0.0.1
          deny: 192.168.10.1
        web-stat-filter:
          enabled: true
                              # 添加过滤规则
          url-pattern: /*
                              # 忽略过滤格式
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  #jpa:
    #database-platform: com.mysql.jdbc.Driver
    #hibernate:
      #ddl-auto: update
    #properties:
      #hibernate:
        #show_sql: true
        #use_sql_comments: true
        #format_sql: true
  #h2:
    #console:
      #enabled: true
      #path: /console
      #settings:
        #trace: false
        #web-allow-others: false

#elasticsearch文档
  #data:
    #elasticsearch:
      #cluster-nodes: localhost:9300
      #client:
        #reactive:
          #connection-timeout: 120
   
#logging:
  #pattern:
    #level: debug

#mybatis
mybatis: 
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zachary.springboot.blog.pushlian.damain
#mybatis.type-aliases-package: 
securityKey: iGwrYVbBtW6nlJJ0IaPsMmeAPXQZVFrDS+tQh69OyT8lsnPdC5hXbXtfQPTao9dq5tXcLItTl6FvHO9485+QAcsSpIxrVMme